ALTER TABLE `candidateApplications`
	ADD `street` varchar(255),
	ADD `houseNumber` varchar(20),
	ADD `postalCode` varchar(10),
	ADD `height` int,
	ADD `weight` int,
	ADD `acceptedEligibility` int NOT NULL DEFAULT 0,
	ADD `acceptedCGU` int NOT NULL DEFAULT 0,
	ADD `consentVersion` varchar(40) NOT NULL DEFAULT 'v1.0',
	ADD `consentedAt` timestamp NULL,
	ADD `candidateSignatureName` varchar(200),
	ADD `candidateSignedAt` timestamp NULL,
	ADD `guardianFullName` varchar(200),
	ADD `guardianEmail` varchar(320),
	ADD `guardianPhone` varchar(50),
	ADD `guardianSignatureName` varchar(200),
	ADD `guardianSignedAt` timestamp NULL,
	ADD `contractVersion` varchar(40),
	ADD `contractStatus` enum('not_started','candidate_signed','guardian_signed','completed','generation_failed') NOT NULL DEFAULT 'not_started',
	ADD `contractPdfKey` text,
	ADD `contractPdfSha256` varchar(64),
	ADD `organizationSignatureName` varchar(200),
	ADD `organizationSignedAt` timestamp NULL;
