import { FormEvent, useState } from "react";
import { Link } from "wouter";
import { Mail, ShieldCheck } from "lucide-react";
import { BRANDING } from "@/config/branding";
import { SEOHead } from "@/components/SEOHead";

export default function ForgotPassword() {
  const [email,setEmail]=useState(""); const [busy,setBusy]=useState(false); const [message,setMessage]=useState(""); const [error,setError]=useState("");
  async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError("");try{const r=await fetch("/api/auth/forgot-password",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({email})});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||"Envoi impossible.");setMessage(d.message);}catch(x){setError(x instanceof Error?x.message:"Envoi impossible.");}finally{setBusy(false);}}
  return <div className="mmd-login-page"><SEOHead title="Mot de passe oublié — Miss & Mister Dour" description="Réinitialisation sécurisée du mot de passe." noindex/><main className="mmd-login-layout"><section className="mmd-login-brand-panel"><img src={BRANDING.logoIdentity} alt="Miss & Mister Dour"/><span>ESPACE SÉCURISÉ · ÉDITION 2027</span><h1>Retrouver<br/><em>votre accès.</em></h1><p>Recevez un lien personnel et temporaire pour choisir un nouveau mot de passe.</p><div className="mmd-login-security"><ShieldCheck/><div><strong>Lien sécurisé</strong><small>Valable 1 heure et utilisable une seule fois.</small></div></div></section><section className="mmd-login-form-panel"><form onSubmit={submit} className="mmd-login-card"><div className="mmd-login-card-head"><Mail/><div><small>RÉINITIALISATION</small><h2>Mot de passe oublié</h2></div></div>{message?<><div className="mmd-login-security"><ShieldCheck/><div><strong>Demande enregistrée</strong><small>{message}</small></div></div><p className="mmd-login-help"><Link href="/login">Retour à la connexion</Link></p></>:<><label><span>Adresse email</span><div className="mmd-login-field"><Mail/><input type="email" autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="vous@exemple.be" required autoFocus/></div></label>{error&&<div className="mmd-login-error">{error}</div>}<button type="submit" className="mmd-login-submit" disabled={busy}>{busy?"Envoi…":"Recevoir le lien"}</button><p className="mmd-login-help"><Link href="/login">Retour à la connexion</Link></p></>}</form></section></main></div>;
}