import { FormEvent, useMemo, useState } from "react";
import { Link } from "wouter";
import { Eye, EyeOff, LockKeyhole, ShieldCheck } from "lucide-react";
import { BRANDING } from "@/config/branding";
import { SEOHead } from "@/components/SEOHead";

export default function ResetPassword(){const token=useMemo(()=>new URLSearchParams(window.location.search).get("token")||"",[]);const[p,setP]=useState("");const[c,setC]=useState("");const[show,setShow]=useState(false);const[busy,setBusy]=useState(false);const[error,setError]=useState("");const[done,setDone]=useState(false);
async function submit(e:FormEvent){e.preventDefault();setError("");if(p.length<10){setError("Le mot de passe doit contenir au moins 10 caractères.");return;}if(p!==c){setError("Les deux mots de passe ne correspondent pas.");return;}setBusy(true);try{const r=await fetch("/api/auth/reset-password",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({token,password:p})});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||"Réinitialisation impossible.");setDone(true);}catch(x){setError(x instanceof Error?x.message:"Réinitialisation impossible.");}finally{setBusy(false);}}
const field=(label:string,value:string,set:(v:string)=>void)=><label><span>{label}</span><div className="mmd-login-field"><LockKeyhole/><input type={show?"text":"password"} autoComplete="new-password" value={value} onChange={e=>set(e.target.value)} minLength={10} required/><button type="button" onClick={()=>setShow(v=>!v)}>{show?<EyeOff/>:<Eye/>}</button></div></label>;
return <div className="mmd-login-page"><SEOHead title="Nouveau mot de passe — Miss & Mister Dour" description="Choisissez un nouveau mot de passe." noindex/><main className="mmd-login-layout"><section className="mmd-login-brand-panel"><img src={BRANDING.logoIdentity} alt="Miss & Mister Dour"/><span>ESPACE SÉCURISÉ · ÉDITION 2027</span><h1>Un nouvel accès.<br/><em>La même aventure.</em></h1><p>Choisissez votre nouveau mot de passe personnel.</p></section><section className="mmd-login-form-panel"><form onSubmit={submit} className="mmd-login-card"><div className="mmd-login-card-head"><LockKeyhole/><div><small>SÉCURITÉ</small><h2>Nouveau mot de passe</h2></div></div>{done?<><div className="mmd-login-security"><ShieldCheck/><div><strong>Mot de passe modifié</strong><small>Vous pouvez maintenant vous connecter.</small></div></div><Link href="/login" className="mmd-login-submit">Se connecter</Link></>:!token?<><div className="mmd-login-error">Ce lien de réinitialisation est incomplet.</div><p className="mmd-login-help"><Link href="/forgot-password">Demander un nouveau lien</Link></p></>:<>{field("Nouveau mot de passe",p,setP)}{field("Confirmer le mot de passe",c,setC)}<p className="mmd-login-help">Minimum 10 caractères.</p>{error&&<div className="mmd-login-error">{error}</div>}<button type="submit" className="mmd-login-submit" disabled={busy}>{busy?"Modification…":"Enregistrer mon nouveau mot de passe"}</button></>}</form></section></main></div>}